services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=emi
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data